baseURL = 'https://www.janosov.com/'
languageCode = 'en-us'
title = 'Milan Janosov, PhD'
theme = 'hyde'

[Params]
description = "Milan Janosov, PhD - Network scientist, data science researcher"
lead = ['Network scientist', 'data science researcher']
copyright = ' '

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
